### PR TITLE
Finished Engish translation

### PR DESCRIPTION
**Pull request by beyondliu**

### CODE REVIEW

**Comment by ZoomQuiet** [comment]
多谢!
但是,能先解决一下冲突嘛?

Checkout via command line

If you cannot merge a pull request automatically here, you have the option of checking it out via command line to resolve conflicts and perform a manual merge.

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b beyondliu-master master
git pull https://github.com/beyondliu/staticpycon.git master

Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff beyondliu-master
git push origin master

**Comment by beyondliu** [comment]
冲突已经解决。请尽快合并。下次请在commit前check一下仓库有无pr。另外最好另有一个发布分支。

**Comment by ZoomQuiet** [comment]
嚓,,,,每天有十多次修订的,
俺先人工完成合并吧,无论如何谢谢了!

**Comment by beyondliu** [comment]
那最后都弄好了后可以再翻译一次。半天时间差不多够了。

**Comment by ZoomQuiet** [comment]
多谢哉 ;-)

On Thu, Sep 10, 2015 at 11:42 AM, Open Source Learning <
notifications@github.com> wrote:

> 那最后都弄好了后可以再翻译一次。半天时间差不多够了。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PyConChina/staticpycon/pull/2#issuecomment-139107675.

## 

Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be
learnning!

**Comment by beyondliu** [comment]
现在深圳。不在北京了。否则可以帮你们北京场做同声翻译。

**Pull request closed without merging**
